services:
  web:
    build: .
    ports:
      - "8000:8000" 
    volumes:
      - .:/app 
    depends_on:
      - db

  db:
    image: "keinos/sqlite3:latest"
    volumes:
      - db_data:/var/lib/sqlite 

volumes:
  db_data:

